language: node_js
node_js:
  - "4"
  - "5"
  - "stable"

sudo: required

services:
  - docker

before_script:
  - npm run start-services
  - npm run lint
  - sleep 3

after_script:
  - npm run coverage
  - npm run check-coverage
  - npm run update-coveralls

notifications:
  email:
    on_success: never
    on_failure: change
